# Generated by Django 4.2.4 on 2023-09-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('telefone', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
